Update 2.7 branch to 2.7.8 to fix [CVE-2023-28756](https://www.ruby-lang.org/en/news/2023/03/30/redos-in-time-cve-2023-28756/)
CircleCI-Public/cimg-ruby pull request #114
Opened 2023-03-30 21:07 UTC by kevinjqiu

2023-03-31 21:38 UTC, ryanbourdais commented
Hi @kevinjqiu  Thank you for the PR.

As mentioned in the readme, edits to this image should be applied to the [Dockerfile.template](https://github.com/CircleCI-Public/cimg-ruby/blob/main/Dockerfile.template) file. Then, during the next release the changes will be published. We don't edit generated Dockerfiles directly.

Would you be able to make these changes?

2023-04-01 00:47 UTC, kevinjqiu commented
@ryanbourdais Thanks for the pointer. Changes made.

2023-04-03 16:49 UTC, akinomaeni commented on 2.7/Dockerfile
> +FROM cimg/base:2023.01
As noted in #116, we need to use ubuntu 20.04.
https://github.com/CircleCI-Public/cimg-ruby/pull/116/files#diff-8d7a21b017921bb88eaf71656b7b5767203db16e8126fc1e5ad2a9ba0bc542f5R9

2023-04-03 17:39 UTC, ryanbourdais requested changes

2023-04-03 17:39 UTC, ryanbourdais commented on 2.7/Dockerfile
> +FROM cimg/base:2023.01
@akinomaeni is correct, I just checked and this build fails currently

2023-04-03 18:44 UTC, ryanbourdais approved these changes
It now builds this image successfully on the platform so it should be good to go, thanks again for contributing!

2023-04-03 20:09 UTC, merged