Add clang-14 for installing gems with Rust extensions
CircleCI-Public/cimg-ruby pull request #128
Opened 2023-04-19 14:54 UTC by HarlemSquirrel

Add clang-14 dependency for installing gems with Rust extensions such as https://github.com/HarlemSquirrel/tzf-rb

2023-05-01 16:30 UTC, JalexChen commented
Hi @HarlemSquirrel,

I've ran this and it looks like it's passing. It looks like the link you're referencing is a personal project. Are there other extensions that would need to include this? Would gcc suffice or is clang a requirement here?

2023-05-01 18:32 UTC, HarlemSquirrel commented
> Hi @HarlemSquirrel,
> 
> I've ran this and it looks like it's passing. It looks like the link you're referencing is a personal project. Are there other extensions that would need to include this? Would gcc suffice or is clang a requirement here?

I believe anything using https://github.com/oxidize-rb/rb-sys/ would need this. That's the defacto way to build Ruby gems with Rust extensions. This is now a supported feature of RubyGems as of https://github.com/rubygems/rubygems/pull/5175

2023-05-02 13:50 UTC, HarlemSquirrel commented
@JalexChen It seems `gcc` is already installed on this image and does not seem to be sufficient.

2023-05-02 18:16 UTC, JalexChen requested changes

2023-05-02 18:16 UTC, JalexChen commented on 3.2/Dockerfile
> +		clang-14 \
Could you please remove this from the 3.2/Dockerfile and instead place these lines in `Dockerfile.template`?

The next update to ruby will include these updates. After the change, you can run `./shared/gen-dockerfiles.sh 3.2.2` for a Dockerfile you can use

2023-05-02 21:10 UTC, JalexChen approved these changes

2023-05-02 21:10 UTC, merged